# ================================
# SpawnServer - Configuraci√≥n
# ================================

# Mensaje de bienvenida que ver√° el jugador al entrar
join-message: "&a¬°Bienvenido %player% al servidor!"

# ¬øMostrar mensaje de bienvenida al entrar? true/false
show-join-message: true

# ¬øEnviar autom√°ticamente al spawn a todos los jugadores al entrar?
always-teleport-to-spawn: true

# Forzar siempre reaparecer en el spawn del plugin

# Forzar siempre reaparecer en el spawn del plugin al morir,
# incluso si el jugador tiene una cama o ancla de reaparici√≥n.
force-spawn-on-death: false

# üõ°Ô∏è (Solo afecta si force-spawn-on-death est√° en false)
# Si est√° en true, entonces el plugin IGNORAR√Å lo que otros plugins como Lands,
# Factions, etc. hayan definido como punto de respawn personalizado.
# Es decir: si no hay cama/ancla, el plugin forzar√° el /spawn del plugin
# incluso si otro plugin intenta establecer su propio respawn (por c√≥digo).
force-override-other-spawn-plugins: false


spawn:
  # Tiempo (en segundos) que tarda en teletransportar al spawn despu√©s de usar /spawn
  delay-seconds: 5

  # Tiempo (en segundos) de cooldown para volver a usar /spawn
  cooldown-seconds: 30

  # Mundos donde est√° permitido usar /spawn
  allowed-worlds:
    - world
    - world_nether

  # ¬øCancelar teletransportaci√≥n si el jugador se mueve?
  cancel-on-move: true

  anti-spam-enabled: true
  anti-spam-seconds: 3


messages:
  only-player: "&cEste comando solo lo puede usar un jugador."

  # El %label% muestra el alias usado para el comando (/spawnserver o /sps)
  # NO BORRAR EL %label%, ES OBLIGATORIO PARA EVITAR ERRORES.
  usage-player: "&cUsa: /%label% set | reload"
  usage-console: "&cUsa: /%label% reload"
  spawn-antispam: "&cNo spamees el /spawn, espera %seconds% segundos."
  spawn-set: "&aSpawn definido correctamente."
  reloaded: "&aSpawnServer recargado correctamente."
  no-permission: "&cNo tienes permiso para usar este comando."
  spawn-wrong-world: "&cNo puedes usar /spawn en este mundo."
  spawn-in-delay: "&aSer√°s teletransportado en %seconds% segundos. No te muevas..."
  spawn-cooldown: "&cDebes esperar %seconds% segundos antes de usar /spawn de nuevo."
  spawn-no-combat: "&cNo puedes usar /spawn mientras est√°s en combate."
  spawn-success: "&aHas sido teletransportado al spawn del servidor."
  spawn-no-spawn: "&cNo hay un spawn definido todav√≠a."
  spawn-moved: "&c¬°Teletransportaci√≥n cancelada!"
